version = 0.1
[default.deploy.parameters]
stack_name = "lambda-type-image"
s3_prefix = "lambda-type-image"
region = "us-east-1"
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = ["MyTestFunction=localhost.localstack.cloud:4510/lambda-type-image/mytestfunction00000000repo"]
resolve_s3 = true
